name: Build (Reusable)

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
        description: "Build configuration (legacy-mono, modern-mono, legacy-il2cpp, modern-il2cpp)"

jobs:
  build:
    name: Build (${{ inputs.config }})
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Show environment
        run: |
          echo "Runner OS: $env:RUNNER_OS"
          echo "Workspace: $env:GITHUB_WORKSPACE"
          dotnet --info

      - name: Restore NuGet packages
        run: dotnet restore UnityUniversalVr.sln /p:Configuration=${{ inputs.config }}

      - name: Build (${{ inputs.config }})
        shell: pwsh
        run: |
          $out = "$env:GITHUB_WORKSPACE\out"
          if (Test-Path $out) {
            Remove-Item -Recurse -Force $out
          }
          msbuild "UnityUniversalVr.sln" /m `
            /p:Configuration=${{ inputs.config }} `
            /p:BepInExDir="$out"

      - name: Pack artifacts (${{ inputs.config }})
        shell: pwsh
        run: |
          $out = "$env:GITHUB_WORKSPACE\out"
          $artDir = "$env:GITHUB_WORKSPACE\artifacts"

          if (!(Test-Path $artDir)) {
            New-Item -ItemType Directory -Path $artDir | Out-Null
          }
          $zip = Join-Path $artDir ("uuvr-${{ inputs.config }}.zip")

          if (Test-Path $zip) {
            Remove-Item -Force $zip
          }

          if (Test-Path $out) {
            Compress-Archive -Path (Join-Path $out '*') -DestinationPath $zip
          } else {
            Write-Error "Expected output folder '$out' not found. Build may have failed."
          }

      - name: Upload artifact (${{ inputs.config }})
        uses: actions/upload-artifact@v4
        with:
          name: uuvr-${{ inputs.config }}
          path: artifacts/uuvr-${{ inputs.config }}.zip
          if-no-files-found: error